import type { CatalogInstrument } from "./types";

// ── East Africa ───────────────────────────────────────────────────────────────
const eastAfrica: CatalogInstrument[] = [
  {
    id: "krar",
    name: "Krar",
    region: "East Africa",
    country: "Ethiopia",
    family: "plucked-string",
    description:
      "A five or six-string bowl-shaped lyre from Ethiopia and Eritrea, traditionally played by the Tigrinya people. Its bright, resonant tone is central to Ethiopian folk music.",
    tuning: "ethiopian-tizita",
    source_family: "plucked",
    tags: ["lyre", "ethiopian", "traditional", "string"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.7,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1800,
      spectral_rolloff: 0.72,
      harmonic_richness: 0.68,
      formant_peaks: [320, 1200, 2800],
      envelope: { attack: 0.02, decay: 0.15, sustain: 0.6, release: 0.4 },
    },
  },
  {
    id: "masenqo",
    name: "Masenqo",
    region: "East Africa",
    country: "Ethiopia",
    family: "bowed-string",
    description:
      "A single-string bowed lute used by Ethiopian azmari musicians. Its nasal, penetrating tone is iconic in Ethiopian traditional music.",
    tuning: "ethiopian-tizita",
    source_family: "bowed",
    tags: ["lute", "ethiopian", "azmari", "bowed"],
    timbre_profile: {
      brightness: 0.72,
      warmth: 0.45,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 2200,
      spectral_rolloff: 0.68,
      harmonic_richness: 0.75,
      formant_peaks: [450, 1800, 3200],
      envelope: { attack: 0.08, decay: 0.1, sustain: 0.8, release: 0.5 },
    },
  },
  {
    id: "begena",
    name: "Begena",
    region: "East Africa",
    country: "Ethiopia",
    family: "plucked-string",
    description:
      "A large ten-string lyre known as the harp of David. Its deep, buzzing tone comes from a special bridge that creates a distinctive rattle.",
    tuning: "ethiopian-bati",
    source_family: "plucked",
    tags: ["lyre", "ethiopian", "sacred", "bass"],
    timbre_profile: {
      brightness: 0.3,
      warmth: 0.9,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 600,
      spectral_rolloff: 0.45,
      harmonic_richness: 0.8,
      formant_peaks: [120, 400, 900],
      envelope: { attack: 0.05, decay: 0.3, sustain: 0.7, release: 0.8 },
    },
  },
  {
    id: "washint",
    name: "Washint",
    region: "East Africa",
    country: "Ethiopia",
    family: "wind",
    description:
      "A traditional Ethiopian end-blown bamboo flute. Produces a breathy, melancholic tone used in pastoral and ceremonial music.",
    tuning: "ethiopian-tizita",
    source_family: "blown",
    tags: ["flute", "ethiopian", "bamboo", "wind"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.5,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1400,
      spectral_rolloff: 0.6,
      harmonic_richness: 0.4,
      formant_peaks: [700, 2100, 4200],
      envelope: { attack: 0.12, decay: 0.05, sustain: 0.85, release: 0.3 },
    },
  },
  {
    id: "kebero",
    name: "Kebero",
    region: "East Africa",
    country: "Ethiopia",
    family: "percussion",
    description:
      "A double-headed conical drum used in Ethiopian Orthodox church music and traditional ceremonies. Produces a deep, resonant boom.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["drum", "ethiopian", "church", "percussion"],
    timbre_profile: {
      brightness: 0.25,
      warmth: 0.85,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 280,
      spectral_rolloff: 0.35,
      harmonic_richness: 0.3,
      formant_peaks: [80, 200, 500],
      envelope: { attack: 0.005, decay: 0.4, sustain: 0.2, release: 0.6 },
    },
  },
  {
    id: "tsinatsil",
    name: "Tsinatsil",
    region: "East Africa",
    country: "Ethiopia",
    family: "percussion",
    description:
      "A sistrum-like rattle used in Ethiopian Orthodox liturgical music. Creates a shimmering, metallic sound when shaken.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["rattle", "ethiopian", "liturgical", "metallic"],
    timbre_profile: {
      brightness: 0.9,
      warmth: 0.15,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 4500,
      spectral_rolloff: 0.88,
      harmonic_richness: 0.5,
      formant_peaks: [2000, 4500, 8000],
      envelope: { attack: 0.001, decay: 0.1, sustain: 0.1, release: 0.2 },
    },
  },
  {
    id: "kirar",
    name: "Kirar",
    region: "East Africa",
    country: "Eritrea",
    family: "plucked-string",
    description:
      "An Eritrean bowl lyre closely related to the Ethiopian Krar. Slightly deeper in tone, used in Tigrinya folk songs and celebrations.",
    tuning: "ethiopian-tizita",
    source_family: "plucked",
    tags: ["lyre", "eritrean", "traditional", "string"],
    timbre_profile: {
      brightness: 0.6,
      warmth: 0.75,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1600,
      spectral_rolloff: 0.7,
      harmonic_richness: 0.65,
      formant_peaks: [300, 1100, 2600],
      envelope: { attack: 0.02, decay: 0.18, sustain: 0.55, release: 0.45 },
    },
  },
  {
    id: "masenko",
    name: "Masenko",
    region: "East Africa",
    country: "Ethiopia",
    family: "bowed-string",
    description:
      "A variant of the Masenqo with a slightly larger body, producing a warmer, fuller tone. Used in southern Ethiopian musical traditions.",
    tuning: "ethiopian-bati",
    source_family: "bowed",
    tags: ["lute", "ethiopian", "bowed", "southern"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.55,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1900,
      spectral_rolloff: 0.65,
      harmonic_richness: 0.72,
      formant_peaks: [400, 1600, 3000],
      envelope: { attack: 0.09, decay: 0.12, sustain: 0.78, release: 0.55 },
    },
  },
];

// ── West Africa ───────────────────────────────────────────────────────────────
const westAfrica: CatalogInstrument[] = [
  {
    id: "kora",
    name: "Kora",
    region: "West Africa",
    country: "Senegal/Gambia",
    family: "plucked-string",
    description:
      "A 21-string bridge harp-lute from West Africa. Its cascading arpeggios and rich harmonic texture make it one of the most complex traditional instruments in the world.",
    tuning: "pentatonic",
    source_family: "plucked",
    tags: ["harp", "west-african", "griot", "string"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.65,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1600,
      spectral_rolloff: 0.68,
      harmonic_richness: 0.78,
      formant_peaks: [280, 1000, 2400],
      envelope: { attack: 0.015, decay: 0.2, sustain: 0.5, release: 0.5 },
    },
  },
  {
    id: "balafon",
    name: "Balafon",
    region: "West Africa",
    country: "Mali/Guinea",
    family: "percussion",
    description:
      "A wooden xylophone with gourd resonators, played by Mande griots. Its warm, woody tone with natural reverb is instantly recognizable.",
    tuning: "pentatonic",
    source_family: "struck",
    tags: ["xylophone", "west-african", "griot", "mallet"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.7,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 900,
      spectral_rolloff: 0.58,
      harmonic_richness: 0.55,
      formant_peaks: [350, 900, 2000],
      envelope: { attack: 0.005, decay: 0.35, sustain: 0.3, release: 0.5 },
    },
  },
  {
    id: "djembe",
    name: "Djembe",
    region: "West Africa",
    country: "Guinea/Mali",
    family: "percussion",
    description:
      "A rope-tuned skin-covered goblet drum. Produces three distinct tones: bass, tone, and slap, each with a unique character.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["drum", "west-african", "goblet", "percussion"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.7,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 500,
      spectral_rolloff: 0.5,
      harmonic_richness: 0.35,
      formant_peaks: [100, 350, 800],
      envelope: { attack: 0.003, decay: 0.25, sustain: 0.15, release: 0.4 },
    },
  },
  {
    id: "ngoni",
    name: "Ngoni",
    region: "West Africa",
    country: "Mali",
    family: "plucked-string",
    description:
      "A small lute with a skin-covered body, ancestor of the banjo. Its buzzy, percussive tone is fundamental to Mande music.",
    tuning: "pentatonic",
    source_family: "plucked",
    tags: ["lute", "west-african", "mande", "banjo-ancestor"],
    timbre_profile: {
      brightness: 0.68,
      warmth: 0.5,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 1400,
      spectral_rolloff: 0.65,
      harmonic_richness: 0.6,
      formant_peaks: [400, 1200, 2500],
      envelope: { attack: 0.01, decay: 0.12, sustain: 0.3, release: 0.3 },
    },
  },
  {
    id: "talking-drum",
    name: "Talking Drum",
    region: "West Africa",
    country: "Nigeria/Ghana",
    family: "percussion",
    description:
      "An hourglass-shaped pressure drum that can mimic the tonal patterns of speech. Pitch is controlled by squeezing the cords.",
    tuning: "custom",
    source_family: "struck",
    tags: ["drum", "west-african", "tonal", "communication"],
    timbre_profile: {
      brightness: 0.45,
      warmth: 0.6,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 600,
      spectral_rolloff: 0.48,
      harmonic_richness: 0.4,
      formant_peaks: [200, 600, 1200],
      envelope: { attack: 0.004, decay: 0.2, sustain: 0.2, release: 0.35 },
    },
  },
  {
    id: "mbira",
    name: "Mbira",
    region: "West Africa",
    country: "Zimbabwe",
    family: "plucked-string",
    description:
      "A thumb piano with metal tines mounted on a wooden board, often placed in a resonating gourd. Its hypnotic, buzzing tone is central to Shona spiritual music.",
    tuning: "custom",
    source_family: "plucked",
    tags: ["thumb-piano", "zimbabwe", "shona", "spiritual"],
    timbre_profile: {
      brightness: 0.6,
      warmth: 0.55,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1100,
      spectral_rolloff: 0.62,
      harmonic_richness: 0.7,
      formant_peaks: [300, 900, 2000],
      envelope: { attack: 0.008, decay: 0.25, sustain: 0.45, release: 0.6 },
    },
  },
  {
    id: "shekere",
    name: "Shekere",
    region: "West Africa",
    country: "Nigeria/Cuba",
    family: "percussion",
    description:
      "A dried gourd covered with a net of beads or shells. Produces a complex, layered rhythmic texture when shaken or struck.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["rattle", "west-african", "gourd", "rhythm"],
    timbre_profile: {
      brightness: 0.75,
      warmth: 0.3,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 3000,
      spectral_rolloff: 0.75,
      harmonic_richness: 0.25,
      formant_peaks: [1500, 3000, 6000],
      envelope: { attack: 0.002, decay: 0.08, sustain: 0.05, release: 0.15 },
    },
  },
];

// ── North Africa / Middle East ────────────────────────────────────────────────
const middleEast: CatalogInstrument[] = [
  {
    id: "oud",
    name: "Oud",
    region: "North Africa / Middle East",
    country: "Arab World",
    family: "plucked-string",
    description:
      "A short-neck fretless lute, the ancestor of the European lute. Its deep, warm tone and microtonal capabilities make it the king of Middle Eastern music.",
    tuning: "arabic-maqam",
    source_family: "plucked",
    tags: ["lute", "arabic", "maqam", "fretless"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.82,
      attack_character: "medium",
      sustain_character: "medium",
      spectral_centroid_hz: 900,
      spectral_rolloff: 0.55,
      harmonic_richness: 0.8,
      formant_peaks: [250, 800, 2000],
      envelope: { attack: 0.025, decay: 0.2, sustain: 0.55, release: 0.5 },
    },
  },
  {
    id: "qanun",
    name: "Qanun",
    region: "North Africa / Middle East",
    country: "Turkey/Egypt",
    family: "plucked-string",
    description:
      "A large zither with 78 strings played with plectra. Its crystalline, harp-like tone is central to Arabic classical music.",
    tuning: "arabic-maqam",
    source_family: "plucked",
    tags: ["zither", "arabic", "classical", "harp-like"],
    timbre_profile: {
      brightness: 0.72,
      warmth: 0.6,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1500,
      spectral_rolloff: 0.7,
      harmonic_richness: 0.72,
      formant_peaks: [400, 1200, 2800],
      envelope: { attack: 0.01, decay: 0.18, sustain: 0.5, release: 0.45 },
    },
  },
  {
    id: "ney",
    name: "Ney",
    region: "North Africa / Middle East",
    country: "Turkey/Iran",
    family: "wind",
    description:
      "An end-blown flute made from a hollow reed. One of the oldest instruments in the world, its breathy, soulful tone is central to Sufi music.",
    tuning: "arabic-maqam",
    source_family: "blown",
    tags: ["flute", "sufi", "reed", "ancient"],
    timbre_profile: {
      brightness: 0.48,
      warmth: 0.58,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1200,
      spectral_rolloff: 0.55,
      harmonic_richness: 0.45,
      formant_peaks: [600, 1800, 3600],
      envelope: { attack: 0.15, decay: 0.05, sustain: 0.88, release: 0.35 },
    },
  },
  {
    id: "darbuka",
    name: "Darbuka",
    region: "North Africa / Middle East",
    country: "Egypt/Turkey",
    family: "percussion",
    description:
      "A goblet-shaped drum with a thin membrane. Produces a sharp, crisp tone used in Arabic, Turkish, and Greek music.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["drum", "arabic", "goblet", "rhythm"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.45,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 800,
      spectral_rolloff: 0.62,
      harmonic_richness: 0.3,
      formant_peaks: [200, 600, 1500],
      envelope: { attack: 0.002, decay: 0.15, sustain: 0.1, release: 0.25 },
    },
  },
  {
    id: "saz",
    name: "Saz",
    region: "North Africa / Middle East",
    country: "Turkey",
    family: "plucked-string",
    description:
      "A long-necked lute central to Turkish folk and Alevi music. Its bright, metallic tone and microtonal frets allow expressive melodic playing.",
    tuning: "arabic-maqam",
    source_family: "plucked",
    tags: ["lute", "turkish", "folk", "long-neck"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.5,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1600,
      spectral_rolloff: 0.68,
      harmonic_richness: 0.65,
      formant_peaks: [350, 1100, 2600],
      envelope: { attack: 0.015, decay: 0.15, sustain: 0.5, release: 0.4 },
    },
  },
  {
    id: "riq",
    name: "Riq",
    region: "North Africa / Middle East",
    country: "Egypt",
    family: "percussion",
    description:
      "A small tambourine with brass cymbals, central to Arabic classical music. Its delicate, shimmering sound provides rhythmic texture.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["tambourine", "arabic", "classical", "metallic"],
    timbre_profile: {
      brightness: 0.85,
      warmth: 0.2,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 3500,
      spectral_rolloff: 0.82,
      harmonic_richness: 0.35,
      formant_peaks: [1800, 3500, 7000],
      envelope: { attack: 0.001, decay: 0.12, sustain: 0.08, release: 0.2 },
    },
  },
  {
    id: "buzuq",
    name: "Buzuq",
    region: "North Africa / Middle East",
    country: "Lebanon/Syria",
    family: "plucked-string",
    description:
      "A long-necked lute from the Levant with a distinctive nasal, buzzing tone. Used in Lebanese and Syrian folk music.",
    tuning: "arabic-maqam",
    source_family: "plucked",
    tags: ["lute", "levantine", "folk", "nasal"],
    timbre_profile: {
      brightness: 0.62,
      warmth: 0.55,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1300,
      spectral_rolloff: 0.63,
      harmonic_richness: 0.7,
      formant_peaks: [380, 1100, 2400],
      envelope: { attack: 0.018, decay: 0.16, sustain: 0.48, release: 0.42 },
    },
  },
];

// ── South Asia ────────────────────────────────────────────────────────────────
const southAsia: CatalogInstrument[] = [
  {
    id: "sitar",
    name: "Sitar",
    region: "South Asia",
    country: "India",
    family: "plucked-string",
    description:
      "A long-necked plucked string instrument with sympathetic strings that resonate beneath the main strings, creating a rich, shimmering halo of sound.",
    tuning: "just-intonation",
    source_family: "plucked",
    tags: ["lute", "indian", "classical", "sympathetic-strings"],
    timbre_profile: {
      brightness: 0.68,
      warmth: 0.6,
      attack_character: "sharp",
      sustain_character: "long",
      spectral_centroid_hz: 1400,
      spectral_rolloff: 0.66,
      harmonic_richness: 0.85,
      formant_peaks: [300, 1000, 2500, 4000],
      envelope: { attack: 0.02, decay: 0.15, sustain: 0.65, release: 0.7 },
    },
  },
  {
    id: "tabla",
    name: "Tabla",
    region: "South Asia",
    country: "India",
    family: "percussion",
    description:
      "A pair of hand drums central to Hindustani classical music. The right drum (dayan) produces melodic tones; the left (bayan) provides bass.",
    tuning: "just-intonation",
    source_family: "struck",
    tags: ["drum", "indian", "classical", "melodic-percussion"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.65,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 700,
      spectral_rolloff: 0.55,
      harmonic_richness: 0.6,
      formant_peaks: [180, 500, 1200],
      envelope: { attack: 0.003, decay: 0.3, sustain: 0.25, release: 0.5 },
    },
  },
  {
    id: "sarod",
    name: "Sarod",
    region: "South Asia",
    country: "India",
    family: "plucked-string",
    description:
      "A fretless lute with a metal fingerboard, producing a deep, weighty tone. Central to Hindustani classical music alongside the sitar.",
    tuning: "just-intonation",
    source_family: "plucked",
    tags: ["lute", "indian", "classical", "fretless", "metal"],
    timbre_profile: {
      brightness: 0.45,
      warmth: 0.78,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 800,
      spectral_rolloff: 0.5,
      harmonic_richness: 0.78,
      formant_peaks: [200, 700, 1800],
      envelope: { attack: 0.03, decay: 0.2, sustain: 0.7, release: 0.65 },
    },
  },
  {
    id: "bansuri",
    name: "Bansuri",
    region: "South Asia",
    country: "India",
    family: "wind",
    description:
      "A transverse bamboo flute used in Hindustani classical music. Its warm, breathy tone can express the full range of human emotion.",
    tuning: "just-intonation",
    source_family: "blown",
    tags: ["flute", "indian", "bamboo", "classical"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.62,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1100,
      spectral_rolloff: 0.52,
      harmonic_richness: 0.42,
      formant_peaks: [550, 1650, 3300],
      envelope: { attack: 0.14, decay: 0.04, sustain: 0.9, release: 0.32 },
    },
  },
  {
    id: "veena",
    name: "Veena",
    region: "South Asia",
    country: "India",
    family: "plucked-string",
    description:
      "One of the oldest Indian instruments, a large plucked lute central to Carnatic classical music. Its resonant, meditative tone is considered divine.",
    tuning: "just-intonation",
    source_family: "plucked",
    tags: ["lute", "indian", "carnatic", "classical", "ancient"],
    timbre_profile: {
      brightness: 0.52,
      warmth: 0.75,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 950,
      spectral_rolloff: 0.54,
      harmonic_richness: 0.8,
      formant_peaks: [250, 850, 2100],
      envelope: { attack: 0.025, decay: 0.22, sustain: 0.68, release: 0.72 },
    },
  },
  {
    id: "sarangi",
    name: "Sarangi",
    region: "South Asia",
    country: "India",
    family: "bowed-string",
    description:
      "A short-necked bowed instrument with sympathetic strings. Its vocal, expressive quality makes it the closest instrument to the human voice in Indian music.",
    tuning: "just-intonation",
    source_family: "bowed",
    tags: ["bowed", "indian", "classical", "vocal", "sympathetic"],
    timbre_profile: {
      brightness: 0.6,
      warmth: 0.7,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1300,
      spectral_rolloff: 0.62,
      harmonic_richness: 0.82,
      formant_peaks: [350, 1100, 2600, 4200],
      envelope: { attack: 0.1, decay: 0.08, sustain: 0.85, release: 0.55 },
    },
  },
  {
    id: "mridangam",
    name: "Mridangam",
    region: "South Asia",
    country: "India",
    family: "percussion",
    description:
      "A double-headed barrel drum, the primary rhythmic instrument of Carnatic classical music. Each head produces distinct tonal qualities.",
    tuning: "just-intonation",
    source_family: "struck",
    tags: ["drum", "indian", "carnatic", "classical", "barrel"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.7,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 600,
      spectral_rolloff: 0.52,
      harmonic_richness: 0.55,
      formant_peaks: [150, 450, 1100],
      envelope: { attack: 0.003, decay: 0.28, sustain: 0.2, release: 0.45 },
    },
  },
];

// ── East Asia ─────────────────────────────────────────────────────────────────
const eastAsia: CatalogInstrument[] = [
  {
    id: "erhu",
    name: "Erhu",
    region: "East Asia",
    country: "China",
    family: "bowed-string",
    description:
      "A two-string bowed instrument, the most expressive in Chinese music. Its singing, vocal quality can convey deep emotion and is central to Chinese opera.",
    tuning: "pentatonic",
    source_family: "bowed",
    tags: ["bowed", "chinese", "classical", "vocal", "two-string"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.55,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1500,
      spectral_rolloff: 0.63,
      harmonic_richness: 0.75,
      formant_peaks: [400, 1400, 3000],
      envelope: { attack: 0.09, decay: 0.07, sustain: 0.88, release: 0.5 },
    },
  },
  {
    id: "guqin",
    name: "Guqin",
    region: "East Asia",
    country: "China",
    family: "plucked-string",
    description:
      "A seven-string zither with over 3000 years of history. Its subtle, meditative tone and complex harmonics make it the instrument of Chinese scholars.",
    tuning: "pentatonic",
    source_family: "plucked",
    tags: ["zither", "chinese", "ancient", "scholar", "meditative"],
    timbre_profile: {
      brightness: 0.42,
      warmth: 0.72,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 700,
      spectral_rolloff: 0.48,
      harmonic_richness: 0.7,
      formant_peaks: [200, 700, 1800],
      envelope: { attack: 0.04, decay: 0.3, sustain: 0.6, release: 0.9 },
    },
  },
  {
    id: "shamisen",
    name: "Shamisen",
    region: "East Asia",
    country: "Japan",
    family: "plucked-string",
    description:
      "A three-string Japanese lute with a distinctive buzzing tone (sawari) created by a special bridge. Central to kabuki and geisha music.",
    tuning: "pentatonic",
    source_family: "plucked",
    tags: ["lute", "japanese", "kabuki", "three-string", "buzzy"],
    timbre_profile: {
      brightness: 0.72,
      warmth: 0.45,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 1700,
      spectral_rolloff: 0.7,
      harmonic_richness: 0.6,
      formant_peaks: [450, 1500, 3200],
      envelope: { attack: 0.01, decay: 0.1, sustain: 0.25, release: 0.3 },
    },
  },
  {
    id: "koto",
    name: "Koto",
    region: "East Asia",
    country: "Japan",
    family: "plucked-string",
    description:
      "A 13-string Japanese zither with movable bridges. Its delicate, crystalline tone is central to Japanese classical music.",
    tuning: "pentatonic",
    source_family: "plucked",
    tags: ["zither", "japanese", "classical", "13-string"],
    timbre_profile: {
      brightness: 0.68,
      warmth: 0.58,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1300,
      spectral_rolloff: 0.66,
      harmonic_richness: 0.68,
      formant_peaks: [350, 1100, 2600],
      envelope: { attack: 0.012, decay: 0.2, sustain: 0.45, release: 0.55 },
    },
  },
  {
    id: "pipa",
    name: "Pipa",
    region: "East Asia",
    country: "China",
    family: "plucked-string",
    description:
      "A four-string Chinese lute with a pear-shaped body. Its bright, percussive attack and expressive range make it one of China's most versatile instruments.",
    tuning: "pentatonic",
    source_family: "plucked",
    tags: ["lute", "chinese", "pear-shaped", "classical"],
    timbre_profile: {
      brightness: 0.75,
      warmth: 0.5,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1800,
      spectral_rolloff: 0.72,
      harmonic_richness: 0.7,
      formant_peaks: [400, 1400, 3000],
      envelope: { attack: 0.008, decay: 0.15, sustain: 0.4, release: 0.4 },
    },
  },
  {
    id: "dizi",
    name: "Dizi",
    region: "East Asia",
    country: "China",
    family: "wind",
    description:
      "A Chinese transverse bamboo flute with a membrane hole that adds a buzzing quality to the tone. Bright and penetrating.",
    tuning: "pentatonic",
    source_family: "blown",
    tags: ["flute", "chinese", "bamboo", "membrane", "bright"],
    timbre_profile: {
      brightness: 0.72,
      warmth: 0.42,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1800,
      spectral_rolloff: 0.7,
      harmonic_richness: 0.5,
      formant_peaks: [900, 2700, 5400],
      envelope: { attack: 0.1, decay: 0.04, sustain: 0.88, release: 0.28 },
    },
  },
  {
    id: "taiko",
    name: "Taiko",
    region: "East Asia",
    country: "Japan",
    family: "percussion",
    description:
      "Large Japanese barrel drums played with thick wooden sticks. Their thunderous, powerful sound is used in festivals, theater, and martial arts.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["drum", "japanese", "festival", "powerful", "barrel"],
    timbre_profile: {
      brightness: 0.35,
      warmth: 0.88,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 200,
      spectral_rolloff: 0.38,
      harmonic_richness: 0.28,
      formant_peaks: [60, 180, 450],
      envelope: { attack: 0.004, decay: 0.5, sustain: 0.3, release: 0.7 },
    },
  },
];

// ── Europe ────────────────────────────────────────────────────────────────────
const europe: CatalogInstrument[] = [
  {
    id: "violin",
    name: "Violin",
    region: "Europe",
    country: "Italy",
    family: "bowed-string",
    description:
      "The soprano of the string family. Its singing, expressive tone spans from delicate whispers to powerful soaring melodies.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["bowed", "european", "classical", "orchestra"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.6,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1600,
      spectral_rolloff: 0.65,
      harmonic_richness: 0.8,
      formant_peaks: [300, 1000, 3000, 5000],
      envelope: { attack: 0.08, decay: 0.06, sustain: 0.9, release: 0.45 },
    },
  },
  {
    id: "cello",
    name: "Cello",
    region: "Europe",
    country: "Italy",
    family: "bowed-string",
    description:
      "The baritone of the string family. Its rich, warm tone is often compared to the human voice and can express profound emotion.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["bowed", "european", "classical", "orchestra", "bass"],
    timbre_profile: {
      brightness: 0.45,
      warmth: 0.85,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 600,
      spectral_rolloff: 0.48,
      harmonic_richness: 0.82,
      formant_peaks: [150, 500, 1500, 3000],
      envelope: { attack: 0.1, decay: 0.07, sustain: 0.92, release: 0.55 },
    },
  },
  {
    id: "flute",
    name: "Flute",
    region: "Europe",
    country: "France",
    family: "wind",
    description:
      "A transverse flute with a pure, bright tone. The modern concert flute can produce a wide range of colors from airy whispers to brilliant high notes.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["flute", "european", "classical", "orchestra", "bright"],
    timbre_profile: {
      brightness: 0.75,
      warmth: 0.38,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 2000,
      spectral_rolloff: 0.72,
      harmonic_richness: 0.35,
      formant_peaks: [1000, 3000, 6000],
      envelope: { attack: 0.12, decay: 0.03, sustain: 0.92, release: 0.25 },
    },
  },
  {
    id: "oboe",
    name: "Oboe",
    region: "Europe",
    country: "France",
    family: "wind",
    description:
      "A double-reed woodwind with a penetrating, nasal tone. Its distinctive sound cuts through an orchestra and is used for tuning.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["reed", "european", "classical", "orchestra", "nasal"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.5,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1500,
      spectral_rolloff: 0.63,
      harmonic_richness: 0.72,
      formant_peaks: [700, 2100, 4200],
      envelope: { attack: 0.11, decay: 0.04, sustain: 0.9, release: 0.28 },
    },
  },
  {
    id: "accordion",
    name: "Accordion",
    region: "Europe",
    country: "France/Germany",
    family: "keyboard",
    description:
      "A free-reed instrument with bellows. Its rich, reedy tone with natural chorus effect is central to French musette, tango, and folk music worldwide.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["reed", "european", "folk", "bellows", "chorus"],
    timbre_profile: {
      brightness: 0.58,
      warmth: 0.65,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1100,
      spectral_rolloff: 0.6,
      harmonic_richness: 0.78,
      formant_peaks: [400, 1200, 2800],
      envelope: { attack: 0.06, decay: 0.02, sustain: 0.95, release: 0.2 },
    },
  },
  {
    id: "bagpipe",
    name: "Bagpipe",
    region: "Europe",
    country: "Scotland",
    family: "wind",
    description:
      "A wind instrument with a continuous drone and a chanter for melody. Its powerful, penetrating sound carries over great distances.",
    tuning: "custom",
    source_family: "blown",
    tags: ["reed", "scottish", "drone", "folk", "outdoor"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.55,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1400,
      spectral_rolloff: 0.67,
      harmonic_richness: 0.75,
      formant_peaks: [500, 1500, 3000],
      envelope: { attack: 0.5, decay: 0.0, sustain: 1.0, release: 0.5 },
    },
  },
  {
    id: "hurdy-gurdy",
    name: "Hurdy-Gurdy",
    region: "Europe",
    country: "France",
    family: "bowed-string",
    description:
      "A mechanical bowed instrument with a rotating wheel and drone strings. Its buzzing, droning tone is central to medieval and folk music.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["bowed", "european", "medieval", "folk", "drone", "mechanical"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.68,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1000,
      spectral_rolloff: 0.57,
      harmonic_richness: 0.8,
      formant_peaks: [300, 900, 2200],
      envelope: { attack: 0.3, decay: 0.0, sustain: 1.0, release: 0.4 },
    },
  },
];

// ── Americas ──────────────────────────────────────────────────────────────────
const americas: CatalogInstrument[] = [
  {
    id: "charango",
    name: "Charango",
    region: "Americas",
    country: "Bolivia/Peru",
    family: "plucked-string",
    description:
      "A small Andean lute traditionally made from an armadillo shell. Its bright, jangly tone is central to Andean folk music.",
    tuning: "12-tet",
    source_family: "plucked",
    tags: ["lute", "andean", "folk", "small", "bright"],
    timbre_profile: {
      brightness: 0.78,
      warmth: 0.42,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 2000,
      spectral_rolloff: 0.75,
      harmonic_richness: 0.62,
      formant_peaks: [500, 1600, 3500],
      envelope: { attack: 0.01, decay: 0.12, sustain: 0.35, release: 0.35 },
    },
  },
  {
    id: "cuatro",
    name: "Cuatro",
    region: "Americas",
    country: "Venezuela",
    family: "plucked-string",
    description:
      "A small four-string guitar from Venezuela, central to joropo music. Its bright, rhythmic strumming drives the llanero musical tradition.",
    tuning: "12-tet",
    source_family: "plucked",
    tags: ["guitar", "venezuelan", "joropo", "folk", "four-string"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.52,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1700,
      spectral_rolloff: 0.68,
      harmonic_richness: 0.65,
      formant_peaks: [420, 1300, 2900],
      envelope: { attack: 0.012, decay: 0.14, sustain: 0.4, release: 0.38 },
    },
  },
  {
    id: "steel-pan",
    name: "Steel Pan",
    region: "Americas",
    country: "Trinidad",
    family: "percussion",
    description:
      "A tuned percussion instrument made from oil drums, invented in Trinidad. Its shimmering, metallic tone is the sound of Caribbean carnival.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["percussion", "caribbean", "trinidad", "metallic", "tuned"],
    timbre_profile: {
      brightness: 0.72,
      warmth: 0.5,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1500,
      spectral_rolloff: 0.7,
      harmonic_richness: 0.65,
      formant_peaks: [500, 1500, 3500],
      envelope: { attack: 0.005, decay: 0.4, sustain: 0.35, release: 0.6 },
    },
  },
  {
    id: "cajon",
    name: "Cajón",
    region: "Americas",
    country: "Peru",
    family: "percussion",
    description:
      "A box-shaped percussion instrument from Peru, played by slapping the front face. Produces bass tones and snare-like sounds.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["drum", "peruvian", "box", "flamenco", "versatile"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.65,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 450,
      spectral_rolloff: 0.5,
      harmonic_richness: 0.3,
      formant_peaks: [100, 350, 900],
      envelope: { attack: 0.003, decay: 0.2, sustain: 0.1, release: 0.35 },
    },
  },
  {
    id: "banjo",
    name: "Banjo",
    region: "Americas",
    country: "United States",
    family: "plucked-string",
    description:
      "A four or five-string instrument with a drum-like body. Its bright, twangy tone is central to bluegrass, country, and old-time music.",
    tuning: "12-tet",
    source_family: "plucked",
    tags: ["plucked", "american", "bluegrass", "country", "twangy"],
    timbre_profile: {
      brightness: 0.82,
      warmth: 0.38,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 2200,
      spectral_rolloff: 0.78,
      harmonic_richness: 0.58,
      formant_peaks: [600, 1800, 4000],
      envelope: { attack: 0.008, decay: 0.1, sustain: 0.2, release: 0.25 },
    },
  },
  {
    id: "marimba",
    name: "Marimba",
    region: "Americas",
    country: "Guatemala/Mexico",
    family: "percussion",
    description:
      "A large xylophone with resonator tubes beneath each bar. Its warm, mellow tone is central to Central American and African music.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["xylophone", "central-american", "mallet", "warm", "resonant"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.75,
      attack_character: "medium",
      sustain_character: "medium",
      spectral_centroid_hz: 800,
      spectral_rolloff: 0.52,
      harmonic_richness: 0.58,
      formant_peaks: [300, 800, 1800],
      envelope: { attack: 0.006, decay: 0.45, sustain: 0.28, release: 0.65 },
    },
  },
  {
    id: "berimbau",
    name: "Berimbau",
    region: "Americas",
    country: "Brazil",
    family: "plucked-string",
    description:
      "A single-string musical bow from Brazil, central to capoeira. A coin or stone pressed against the string changes its pitch.",
    tuning: "custom",
    source_family: "plucked",
    tags: ["bow", "brazilian", "capoeira", "single-string", "rhythmic"],
    timbre_profile: {
      brightness: 0.6,
      warmth: 0.55,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 1000,
      spectral_rolloff: 0.6,
      harmonic_richness: 0.45,
      formant_peaks: [250, 800, 2000],
      envelope: { attack: 0.01, decay: 0.15, sustain: 0.2, release: 0.3 },
    },
  },
];

// ── Electronic ────────────────────────────────────────────────────────────────
const electronic: CatalogInstrument[] = [
  {
    id: "moog-synth",
    name: "Moog Synthesizer",
    region: "Electronic",
    country: "United States",
    family: "electronic",
    description:
      "The pioneering analog synthesizer by Robert Moog. Its warm, fat bass tones and expressive filter sweeps defined the sound of electronic music.",
    tuning: "12-tet",
    source_family: "electronic",
    tags: ["synth", "analog", "moog", "bass", "filter"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.82,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 800,
      spectral_rolloff: 0.55,
      harmonic_richness: 0.88,
      formant_peaks: [200, 600, 1500],
      envelope: { attack: 0.05, decay: 0.2, sustain: 0.75, release: 0.4 },
    },
  },
  {
    id: "rhodes-piano",
    name: "Rhodes Piano",
    region: "Electronic",
    country: "United States",
    family: "electronic",
    description:
      "An electric piano with metal tines struck by hammers. Its warm, bell-like tone with natural tremolo became the sound of jazz fusion and soul.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["electric-piano", "rhodes", "jazz", "soul", "bell-like"],
    timbre_profile: {
      brightness: 0.6,
      warmth: 0.7,
      attack_character: "medium",
      sustain_character: "medium",
      spectral_centroid_hz: 1000,
      spectral_rolloff: 0.6,
      harmonic_richness: 0.72,
      formant_peaks: [300, 900, 2200],
      envelope: { attack: 0.01, decay: 0.3, sustain: 0.55, release: 0.5 },
    },
  },
  {
    id: "wurlitzer",
    name: "Wurlitzer",
    region: "Electronic",
    country: "United States",
    family: "electronic",
    description:
      "An electric piano with a reedy, buzzy tone distinct from the Rhodes. Its gritty character is central to rock, soul, and funk music.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["electric-piano", "wurlitzer", "rock", "soul", "reedy"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.58,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1200,
      spectral_rolloff: 0.63,
      harmonic_richness: 0.68,
      formant_peaks: [400, 1200, 2800],
      envelope: { attack: 0.008, decay: 0.25, sustain: 0.5, release: 0.4 },
    },
  },
  {
    id: "theremin",
    name: "Theremin",
    region: "Electronic",
    country: "Russia",
    family: "electronic",
    description:
      "The first electronic instrument, played without physical contact. Two antennas control pitch and volume, producing an eerie, vocal tone.",
    tuning: "custom",
    source_family: "electronic",
    tags: ["theremin", "electronic", "contactless", "eerie", "vocal"],
    timbre_profile: {
      brightness: 0.58,
      warmth: 0.62,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1100,
      spectral_rolloff: 0.58,
      harmonic_richness: 0.65,
      formant_peaks: [350, 1100, 2600],
      envelope: { attack: 0.2, decay: 0.05, sustain: 0.92, release: 0.35 },
    },
  },
  {
    id: "mellotron",
    name: "Mellotron",
    region: "Electronic",
    country: "United Kingdom",
    family: "electronic",
    description:
      "A keyboard instrument that plays pre-recorded tape loops of real instruments. Its slightly degraded, haunting quality defined the sound of 1960s psychedelic rock.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["tape", "mellotron", "psychedelic", "strings", "flute", "choir"],
    timbre_profile: {
      brightness: 0.52,
      warmth: 0.72,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 900,
      spectral_rolloff: 0.54,
      harmonic_richness: 0.75,
      formant_peaks: [280, 900, 2200],
      envelope: { attack: 0.15, decay: 0.05, sustain: 0.88, release: 0.4 },
    },
  },
  {
    id: "vocoder",
    name: "Vocoder",
    region: "Electronic",
    country: "Germany",
    family: "electronic",
    description:
      "A speech synthesizer that imposes the spectral characteristics of a voice onto a synthesizer carrier signal, creating robotic vocal effects.",
    tuning: "12-tet",
    source_family: "electronic",
    tags: ["vocoder", "electronic", "robotic", "voice", "synthesis"],
    timbre_profile: {
      brightness: 0.62,
      warmth: 0.55,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1200,
      spectral_rolloff: 0.62,
      harmonic_richness: 0.7,
      formant_peaks: [500, 1500, 2500, 3500],
      envelope: { attack: 0.08, decay: 0.05, sustain: 0.9, release: 0.3 },
    },
  },
  {
    id: "ondes-martenot",
    name: "Ondes Martenot",
    region: "Electronic",
    country: "France",
    family: "electronic",
    description:
      "An early electronic instrument with a keyboard and a ring controller for expressive pitch glides. Its ethereal, singing tone was used by Messiaen and in film scores.",
    tuning: "custom",
    source_family: "electronic",
    tags: ["electronic", "french", "ethereal", "glide", "messiaen"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.68,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 950,
      spectral_rolloff: 0.56,
      harmonic_richness: 0.72,
      formant_peaks: [300, 950, 2400],
      envelope: { attack: 0.18, decay: 0.04, sustain: 0.94, release: 0.38 },
    },
  },
];

// ── Full catalog ──────────────────────────────────────────────────────────────
export const CATALOG: CatalogInstrument[] = [
  ...eastAfrica,
  ...westAfrica,
  ...middleEast,
  ...southAsia,
  ...eastAsia,
  ...europe,
  ...americas,
  ...electronic,
];

export const CATALOG_REGIONS = [
  "East Africa",
  "West Africa",
  "North Africa / Middle East",
  "South Asia",
  "East Asia",
  "Europe",
  "Americas",
  "Electronic",
] as const;
