/**
 * Country to flag emoji mapping
 */

export const COUNTRY_FLAGS: Record<string, string> = {
  Ethiopia: "🇪🇹",
  Eritrea: "🇪🇷",
  Senegal: "🇸🇳",
  Mali: "🇲🇱",
  Guinea: "🇬🇳",
  Ghana: "🇬🇭",
  Nigeria: "🇳🇬",
  Egypt: "🇪🇬",
  Morocco: "🇲🇦",
  Turkey: "🇹🇷",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Syria: "🇸🇾",
  Lebanon: "🇱🇧",
  India: "🇮🇳",
  Pakistan: "🇵🇰",
  Bangladesh: "🇧🇩",
  China: "🇨🇳",
  Japan: "🇯🇵",
  Korea: "🇰🇷",
  Indonesia: "🇮🇩",
  Thailand: "🇹🇭",
  Vietnam: "🇻🇳",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Italy: "🇮🇹",
  Spain: "🇪🇸",
  UK: "🇬🇧",
  Ireland: "🇮🇪",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Russia: "🇷🇺",
  USA: "🇺🇸",
  Mexico: "🇲🇽",
  Brazil: "🇧🇷",
  Argentina: "🇦🇷",
  Peru: "🇵🇪",
  Colombia: "🇨🇴",
  Cuba: "🇨🇺",
  Jamaica: "🇯🇲",
  "Trinidad and Tobago": "🇹🇹",
  Venezuela: "🇻🇪",
  Chile: "🇨🇱",
  Bolivia: "🇧🇴",
  Ecuador: "🇪🇨",
  Paraguay: "🇵🇾",
  Uruguay: "🇺🇾",
  "South Africa": "🇿🇦",
  Kenya: "🇰🇪",
  Tanzania: "🇹🇿",
  Uganda: "🇺🇬",
  Zimbabwe: "🇿🇼",
  Mozambique: "🇲🇿",
  Angola: "🇦🇴",
  Cameroon: "🇨🇲",
  "Ivory Coast": "🇨🇮",
  "Burkina Faso": "🇧🇫",
  Benin: "🇧🇯",
  Togo: "🇹🇬",
  "Sierra Leone": "🇸🇱",
  Liberia: "🇱🇷",
  Gambia: "🇬🇲",
  "Guinea-Bissau": "🇬🇼",
  "Cape Verde": "🇨🇻",
  "São Tomé and Príncipe": "🇸🇹",
  Gabon: "🇬🇦",
  "Republic of the Congo": "🇨🇬",
  "Democratic Republic of the Congo": "🇨🇩",
  "Central African Republic": "🇨🇫",
  Chad: "🇹🇩",
  Niger: "🇳🇪",
  Mauritania: "🇲🇷",
  "Western Sahara": "🇪🇭",
  Sudan: "🇸🇩",
  "South Sudan": "🇸�S",
  Somalia: "🇸🇴",
  Djibouti: "🇩🇯",
  Comoros: "🇰🇲",
  Seychelles: "🇸🇨",
  Mauritius: "🇲🇺",
  Madagascar: "🇲🇬",
  Malawi: "🇲🇼",
  Zambia: "🇿🇲",
  Botswana: "🇧🇼",
  Namibia: "🇳🇦",
  Lesotho: "🇱🇸",
  Eswatini: "🇸🇿",
  Rwanda: "🇷🇼",
  Burundi: "🇧🇮",
  // Electronic/Synthetic
  Electronic: "🎹",
  Synthetic: "🎛",
  Digital: "💻",
};

export function getCountryFlag(country: string): string {
  return COUNTRY_FLAGS[country] || "🌍";
}
