/**
 * Western instrument catalog entries.
 * These instruments use real sample packs downloaded from GitHub Releases.
 * The sample packs are managed by the SampleLibrary panel.
 */

import type { CatalogInstrument } from "./types";

export const WESTERN_INSTRUMENTS: CatalogInstrument[] = [
  {
    id: "drums-studio",
    name: "Studio Drum Kit",
    region: "Europe",
    country: "United States",
    family: "percussion",
    description:
      "Close-miked acoustic studio drum kit. Punchy kick, crisp snare, articulate hi-hats. Recorded with professional condenser microphones.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["drums", "percussion", "studio", "acoustic", "kit"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.5,
      attack_character: "sharp",
      sustain_character: "short",
      spectral_centroid_hz: 800,
      spectral_rolloff: 0.7,
      harmonic_richness: 0.4,
      formant_peaks: [],
      envelope: { attack: 0.001, decay: 0.3, sustain: 0.0, release: 0.1 },
    },
  },
  {
    id: "drums-jazz",
    name: "Jazz Brushed Kit",
    region: "Europe",
    country: "United States",
    family: "percussion",
    description:
      "Warm jazz drum kit recorded with brushes. Intimate room sound, soft attack, perfect for jazz and acoustic music.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["drums", "jazz", "brushed", "acoustic", "kit"],
    timbre_profile: {
      brightness: 0.4,
      warmth: 0.7,
      attack_character: "soft",
      sustain_character: "short",
      spectral_centroid_hz: 400,
      spectral_rolloff: 0.5,
      harmonic_richness: 0.3,
      formant_peaks: [],
      envelope: { attack: 0.005, decay: 0.4, sustain: 0.0, release: 0.15 },
    },
  },
  {
    id: "drums-orchestral",
    name: "Orchestral Percussion",
    region: "Europe",
    country: "United States",
    family: "percussion",
    description:
      "Concert bass drum, snare, timpani, cymbals, triangle, tambourine. Full orchestral percussion section.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["orchestral", "percussion", "classical", "concert"],
    timbre_profile: {
      brightness: 0.6,
      warmth: 0.6,
      attack_character: "medium",
      sustain_character: "medium",
      spectral_centroid_hz: 600,
      spectral_rolloff: 0.6,
      harmonic_richness: 0.5,
      formant_peaks: [],
      envelope: { attack: 0.002, decay: 0.5, sustain: 0.0, release: 0.3 },
    },
  },
  {
    id: "piano-grand",
    name: "Yamaha C5 Grand Piano",
    region: "Europe",
    country: "Germany",
    family: "keyboard",
    description:
      "Salamander Grand Piano — Yamaha C5 grand recorded in a professional studio. 16 velocity layers, 3 round-robin variations. The gold standard of free piano samples.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["piano", "grand", "acoustic", "classical", "yamaha"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.6,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1200,
      spectral_rolloff: 0.75,
      harmonic_richness: 0.85,
      formant_peaks: [],
      envelope: { attack: 0.002, decay: 1.5, sustain: 0.7, release: 0.8 },
    },
  },
  {
    id: "piano-upright",
    name: "Kawai Upright Piano",
    region: "Europe",
    country: "Germany",
    family: "keyboard",
    description:
      "Warm upright piano with a more intimate character than a grand. Perfect for pop, jazz, and singer-songwriter music.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["piano", "upright", "acoustic", "warm", "intimate"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.75,
      attack_character: "medium",
      sustain_character: "medium",
      spectral_centroid_hz: 900,
      spectral_rolloff: 0.65,
      harmonic_richness: 0.75,
      formant_peaks: [],
      envelope: { attack: 0.003, decay: 1.2, sustain: 0.6, release: 0.6 },
    },
  },
  {
    id: "piano-steinway",
    name: "Steinway Model D",
    region: "Europe",
    country: "Germany",
    family: "keyboard",
    description:
      "University of Iowa Steinway Model D. Classical character, bright and projecting. Public domain recording.",
    tuning: "12-tet",
    source_family: "struck",
    tags: ["piano", "steinway", "classical", "concert"],
    timbre_profile: {
      brightness: 0.75,
      warmth: 0.55,
      attack_character: "sharp",
      sustain_character: "long",
      spectral_centroid_hz: 1400,
      spectral_rolloff: 0.8,
      harmonic_richness: 0.9,
      formant_peaks: [],
      envelope: { attack: 0.001, decay: 1.8, sustain: 0.75, release: 1.0 },
    },
  },
  {
    id: "violin",
    name: "Violin",
    region: "Europe",
    country: "Italy",
    family: "bowed-string",
    description:
      "Full-range violin with sustain, pizzicato, and staccato articulations. VSCO 2 Community Edition.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["violin", "strings", "orchestral", "classical"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.6,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 2000,
      spectral_rolloff: 0.7,
      harmonic_richness: 0.8,
      formant_peaks: [800, 2400],
      envelope: { attack: 0.05, decay: 0.1, sustain: 0.9, release: 0.3 },
    },
  },
  {
    id: "viola",
    name: "Viola",
    region: "Europe",
    country: "Italy",
    family: "bowed-string",
    description: "Warm, dark viola with sustain and pizzicato articulations.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["viola", "strings", "orchestral", "classical"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.75,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1400,
      spectral_rolloff: 0.65,
      harmonic_richness: 0.75,
      formant_peaks: [600, 1800],
      envelope: { attack: 0.06, decay: 0.1, sustain: 0.9, release: 0.35 },
    },
  },
  {
    id: "cello",
    name: "Cello",
    region: "Europe",
    country: "Italy",
    family: "bowed-string",
    description:
      "Rich, resonant cello with sustain, pizzicato, and staccato articulations.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["cello", "strings", "orchestral", "classical"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.85,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 800,
      spectral_rolloff: 0.6,
      harmonic_richness: 0.8,
      formant_peaks: [400, 1200],
      envelope: { attack: 0.07, decay: 0.1, sustain: 0.9, release: 0.4 },
    },
  },
  {
    id: "double-bass",
    name: "Double Bass",
    region: "Europe",
    country: "Italy",
    family: "bowed-string",
    description:
      "Deep, powerful double bass with sustain and pizzicato articulations.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["double bass", "bass", "strings", "orchestral"],
    timbre_profile: {
      brightness: 0.35,
      warmth: 0.95,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 300,
      spectral_rolloff: 0.45,
      harmonic_richness: 0.7,
      formant_peaks: [200, 600],
      envelope: { attack: 0.08, decay: 0.1, sustain: 0.9, release: 0.5 },
    },
  },
  {
    id: "string-ensemble",
    name: "String Ensemble",
    region: "Europe",
    country: "United States",
    family: "bowed-string",
    description:
      "Full string ensemble with sustain and tremolo articulations. Versilian Chamber Orchestra.",
    tuning: "12-tet",
    source_family: "bowed",
    tags: ["strings", "ensemble", "orchestral", "section"],
    timbre_profile: {
      brightness: 0.6,
      warmth: 0.7,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1200,
      spectral_rolloff: 0.65,
      harmonic_richness: 0.85,
      formant_peaks: [600, 1800],
      envelope: { attack: 0.1, decay: 0.1, sustain: 0.95, release: 0.5 },
    },
  },
  {
    id: "trumpet",
    name: "Trumpet",
    region: "Europe",
    country: "United States",
    family: "wind",
    description:
      "Bright, projecting trumpet with sustain, staccato, and sforzando articulations.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["trumpet", "brass", "orchestral", "jazz"],
    timbre_profile: {
      brightness: 0.85,
      warmth: 0.4,
      attack_character: "sharp",
      sustain_character: "long",
      spectral_centroid_hz: 2500,
      spectral_rolloff: 0.8,
      harmonic_richness: 0.9,
      formant_peaks: [1200, 3000],
      envelope: { attack: 0.02, decay: 0.05, sustain: 0.95, release: 0.15 },
    },
  },
  {
    id: "trombone",
    name: "Trombone",
    region: "Europe",
    country: "United States",
    family: "wind",
    description:
      "Warm, powerful trombone with sustain and staccato articulations.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["trombone", "brass", "orchestral", "jazz"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.7,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1200,
      spectral_rolloff: 0.7,
      harmonic_richness: 0.85,
      formant_peaks: [600, 1800],
      envelope: { attack: 0.03, decay: 0.05, sustain: 0.95, release: 0.2 },
    },
  },
  {
    id: "french-horn",
    name: "French Horn",
    region: "Europe",
    country: "Germany",
    family: "wind",
    description:
      "Rich, mellow French horn with sustain and staccato articulations.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["french horn", "brass", "orchestral", "classical"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.8,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 900,
      spectral_rolloff: 0.65,
      harmonic_richness: 0.8,
      formant_peaks: [500, 1500],
      envelope: { attack: 0.05, decay: 0.05, sustain: 0.95, release: 0.25 },
    },
  },
  {
    id: "tuba",
    name: "Tuba",
    region: "Europe",
    country: "Germany",
    family: "wind",
    description: "Deep, powerful tuba with sustain articulation.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["tuba", "brass", "orchestral", "bass"],
    timbre_profile: {
      brightness: 0.4,
      warmth: 0.9,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 400,
      spectral_rolloff: 0.5,
      harmonic_richness: 0.75,
      formant_peaks: [200, 800],
      envelope: { attack: 0.06, decay: 0.05, sustain: 0.95, release: 0.3 },
    },
  },
  {
    id: "brass-ensemble",
    name: "Brass Ensemble",
    region: "Europe",
    country: "United States",
    family: "wind",
    description:
      "Full brass section with sustain and marcato articulations. Sonatina Symphonic Orchestra.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["brass", "ensemble", "orchestral", "section"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.65,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1500,
      spectral_rolloff: 0.72,
      harmonic_richness: 0.88,
      formant_peaks: [800, 2000],
      envelope: { attack: 0.04, decay: 0.05, sustain: 0.95, release: 0.25 },
    },
  },
  {
    id: "flute",
    name: "Flute",
    region: "Europe",
    country: "United States",
    family: "wind",
    description:
      "Clear, bright flute. University of Iowa recording, public domain.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["flute", "woodwind", "orchestral", "classical"],
    timbre_profile: {
      brightness: 0.8,
      warmth: 0.4,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 2800,
      spectral_rolloff: 0.75,
      harmonic_richness: 0.5,
      formant_peaks: [2000, 4000],
      envelope: { attack: 0.04, decay: 0.05, sustain: 0.9, release: 0.2 },
    },
  },
  {
    id: "clarinet",
    name: "Clarinet",
    region: "Europe",
    country: "United States",
    family: "wind",
    description:
      "Warm, woody clarinet. University of Iowa recording, public domain.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["clarinet", "woodwind", "orchestral", "jazz"],
    timbre_profile: {
      brightness: 0.6,
      warmth: 0.65,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1500,
      spectral_rolloff: 0.65,
      harmonic_richness: 0.7,
      formant_peaks: [1000, 2500],
      envelope: { attack: 0.03, decay: 0.05, sustain: 0.9, release: 0.15 },
    },
  },
  {
    id: "oboe",
    name: "Oboe",
    region: "Europe",
    country: "United States",
    family: "wind",
    description:
      "Penetrating, nasal oboe. University of Iowa recording, public domain.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["oboe", "woodwind", "orchestral", "classical"],
    timbre_profile: {
      brightness: 0.75,
      warmth: 0.45,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 2200,
      spectral_rolloff: 0.72,
      harmonic_richness: 0.85,
      formant_peaks: [1200, 3000],
      envelope: { attack: 0.03, decay: 0.05, sustain: 0.9, release: 0.15 },
    },
  },
  {
    id: "bassoon",
    name: "Bassoon",
    region: "Europe",
    country: "United States",
    family: "wind",
    description:
      "Dark, reedy bassoon. University of Iowa recording, public domain.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["bassoon", "woodwind", "orchestral", "classical"],
    timbre_profile: {
      brightness: 0.45,
      warmth: 0.8,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 700,
      spectral_rolloff: 0.6,
      harmonic_richness: 0.8,
      formant_peaks: [400, 1200],
      envelope: { attack: 0.04, decay: 0.05, sustain: 0.9, release: 0.2 },
    },
  },
  {
    id: "alto-saxophone",
    name: "Alto Saxophone",
    region: "Europe",
    country: "United States",
    family: "wind",
    description:
      "Warm, expressive alto saxophone. University of Iowa recording, public domain.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["saxophone", "alto", "woodwind", "jazz"],
    timbre_profile: {
      brightness: 0.65,
      warmth: 0.7,
      attack_character: "medium",
      sustain_character: "long",
      spectral_centroid_hz: 1600,
      spectral_rolloff: 0.68,
      harmonic_richness: 0.82,
      formant_peaks: [800, 2200],
      envelope: { attack: 0.03, decay: 0.05, sustain: 0.9, release: 0.2 },
    },
  },
  {
    id: "guitar-nylon",
    name: "Classical Nylon Guitar",
    region: "Europe",
    country: "Spain",
    family: "plucked-string",
    description:
      "Warm classical nylon-string guitar. VSCO 2 Community Edition.",
    tuning: "12-tet",
    source_family: "plucked",
    tags: ["guitar", "classical", "nylon", "acoustic", "spanish"],
    timbre_profile: {
      brightness: 0.5,
      warmth: 0.75,
      attack_character: "medium",
      sustain_character: "medium",
      spectral_centroid_hz: 900,
      spectral_rolloff: 0.6,
      harmonic_richness: 0.7,
      formant_peaks: [500, 1500],
      envelope: { attack: 0.005, decay: 0.8, sustain: 0.3, release: 0.5 },
    },
  },
  {
    id: "guitar-steel",
    name: "Steel Acoustic Guitar",
    region: "Europe",
    country: "United States",
    family: "plucked-string",
    description: "Bright steel-string acoustic guitar. Versilian Studios.",
    tuning: "12-tet",
    source_family: "plucked",
    tags: ["guitar", "acoustic", "steel", "folk", "country"],
    timbre_profile: {
      brightness: 0.7,
      warmth: 0.6,
      attack_character: "sharp",
      sustain_character: "medium",
      spectral_centroid_hz: 1400,
      spectral_rolloff: 0.68,
      harmonic_richness: 0.75,
      formant_peaks: [700, 2000],
      envelope: { attack: 0.003, decay: 0.7, sustain: 0.25, release: 0.4 },
    },
  },
  {
    id: "bass-upright",
    name: "Upright Bass",
    region: "Europe",
    country: "United States",
    family: "plucked-string",
    description:
      "Warm upright bass with arco (bowed) and pizzicato articulations. University of Iowa, public domain.",
    tuning: "12-tet",
    source_family: "plucked",
    tags: ["bass", "upright", "double bass", "jazz", "classical"],
    timbre_profile: {
      brightness: 0.35,
      warmth: 0.9,
      attack_character: "medium",
      sustain_character: "medium",
      spectral_centroid_hz: 250,
      spectral_rolloff: 0.45,
      harmonic_richness: 0.7,
      formant_peaks: [150, 500],
      envelope: { attack: 0.01, decay: 0.5, sustain: 0.6, release: 0.3 },
    },
  },
  {
    id: "choir-aah",
    name: "Choir Aah",
    region: "Europe",
    country: "United States",
    family: "voice",
    description: "Mixed choir singing Aah vowel. VSCO 2 Community Edition.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["choir", "vocal", "aah", "orchestral", "choral"],
    timbre_profile: {
      brightness: 0.55,
      warmth: 0.7,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 1000,
      spectral_rolloff: 0.62,
      harmonic_richness: 0.75,
      formant_peaks: [800, 1200, 2500],
      envelope: { attack: 0.1, decay: 0.05, sustain: 0.95, release: 0.4 },
    },
  },
  {
    id: "choir-ooh",
    name: "Choir Ooh",
    region: "Europe",
    country: "United States",
    family: "voice",
    description: "Mixed choir singing Ooh vowel. VSCO 2 Community Edition.",
    tuning: "12-tet",
    source_family: "blown",
    tags: ["choir", "vocal", "ooh", "orchestral", "choral"],
    timbre_profile: {
      brightness: 0.45,
      warmth: 0.75,
      attack_character: "soft",
      sustain_character: "long",
      spectral_centroid_hz: 700,
      spectral_rolloff: 0.55,
      harmonic_richness: 0.7,
      formant_peaks: [400, 800, 2000],
      envelope: { attack: 0.12, decay: 0.05, sustain: 0.95, release: 0.45 },
    },
  },
];
