//! Build script for aether-plugin.
//!
//! Reads `AETHER_INSTRUMENT_JSON` env var (a JSON string of a `SamplerInstrument`).
//! For each zone's `file_path`, tries to embed the audio bytes as a static byte array
//! in a generated Rust source file (`OUT_DIR/embedded_audio.rs`).
//!
//! If a file doesn't exist, the zone is skipped gracefully — the plugin will simply
//! have no audio for that zone at runtime.

use std::env;
use std::fs;
use std::path::Path;

// Minimal structs to parse just the fields we need from SamplerInstrument JSON.
#[derive(serde::Deserialize)]
struct InstrumentJson {
    #[serde(default)]
    zones: Vec<ZoneJson>,
}

#[derive(serde::Deserialize)]
struct ZoneJson {
    id: String,
    file_path: String,
}

fn main() {
    // Tell Cargo to re-run this script if the env var changes.
    println!("cargo:rerun-if-env-changed=AETHER_INSTRUMENT_JSON");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("embedded_audio.rs");

    let instrument_json = env::var("AETHER_INSTRUMENT_JSON").unwrap_or_default();

    let mut generated = String::new();
    generated.push_str("// Auto-generated by aether-plugin build.rs — do not edit.\n");
    generated.push_str("// Maps zone id → embedded audio bytes.\n\n");
    generated.push_str("pub static EMBEDDED_ZONES: &[(&str, &[u8])] = &[\n");

    if !instrument_json.is_empty() {
        match serde_json::from_str::<InstrumentJson>(&instrument_json) {
            Ok(inst) => {
                for zone in &inst.zones {
                    let audio_path = Path::new(&zone.file_path);
                    if audio_path.exists() {
                        // Emit an include_bytes! entry for this zone.
                        // Use the canonical absolute path so include_bytes! can find it.
                        let abs = audio_path
                            .canonicalize()
                            .unwrap_or_else(|_| audio_path.to_path_buf());
                        let abs_str = abs.to_string_lossy().replace('\\', "/");
                        generated.push_str(&format!(
                            "    ({:?}, include_bytes!({:?})),\n",
                            zone.id, abs_str
                        ));
                        println!("cargo:rerun-if-changed={}", abs.display());
                    } else {
                        // File doesn't exist — skip gracefully.
                        eprintln!(
                            "aether-plugin build.rs: zone '{}' file '{}' not found — skipping.",
                            zone.id, zone.file_path
                        );
                    }
                }
            }
            Err(e) => {
                eprintln!("aether-plugin build.rs: failed to parse AETHER_INSTRUMENT_JSON: {e}");
            }
        }
    }

    generated.push_str("];\n");

    fs::write(&out_path, generated).expect("Failed to write embedded_audio.rs");
}
