#[cfg(feature = "chorus")]
pub mod chorus;
#[cfg(feature = "compressor")]
pub mod compressor;
#[cfg(feature = "delay")]
pub mod delay;
#[cfg(feature = "envelope")]
pub mod envelope;
#[cfg(feature = "eq")]
pub mod eq;
#[cfg(feature = "filter")]
pub mod filter;
#[cfg(feature = "formant")]
pub mod formant;
#[cfg(feature = "gain")]
pub mod gain;
#[cfg(feature = "gate")]
pub mod gate;
#[cfg(feature = "granular")]
pub mod granular;
#[cfg(feature = "karplus-strong")]
pub mod karplus_strong;
#[cfg(feature = "lfo")]
pub mod lfo;
#[cfg(feature = "limiter")]
pub mod limiter;
#[cfg(feature = "mixer")]
pub mod mixer;
#[cfg(feature = "moog-ladder")]
pub mod moog_ladder;
#[cfg(feature = "oscillator")]
pub mod oscillator;
#[cfg(feature = "panner")]
pub mod panner;
#[cfg(feature = "record")]
pub mod record;
#[cfg(feature = "reverb")]
pub mod reverb;
#[cfg(feature = "scope")]
pub mod scope;
#[cfg(feature = "waveshaper")]
pub mod waveshaper;

#[cfg(test)]
mod tests {
    mod regression;
}

#[cfg(feature = "chorus")]
pub use chorus::Chorus;
#[cfg(feature = "compressor")]
pub use compressor::Compressor;
#[cfg(feature = "eq")]
pub use eq::ParametricEq;
#[cfg(feature = "gate")]
pub use gate::Gate;
#[cfg(feature = "limiter")]
pub use limiter::Limiter;
#[cfg(feature = "panner")]
pub use panner::Panner;
#[cfg(feature = "record")]
pub use record::RecordNode;
#[cfg(feature = "scope")]
pub use scope::ScopeNode;
#[cfg(feature = "waveshaper")]
pub use waveshaper::Waveshaper;
